x = (input('Digite Algo: '))
print(type(x))
print('palavra?', x.isalpha())
print('número?', x.isnumeric())
print('alfanumérico?', x.isalnum())
print('minúsculo?', x.islower())
print('maiúsculo?', x.isupper())
print('espaço?', x.isspace())
print('capitalizado?', x.istitle())
